name: Sync All Branches

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 0:00 触发一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: CyrusZhou-CN/odoo
          token: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Token 进行认证

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/odoo/odoo.git

      - name: Fetch all branches from upstream
        run: |
          git fetch upstream

      - name: Sync branches
        run: |
          for branch in $(git branch -r | grep 'upstream/' | grep -v '\->' | sed 's/upstream\///'); do
            echo "Processing branch: $branch"
            if git show-ref --verify --quiet "refs/heads/$branch"; then
              git checkout "$branch"
              git pull upstream "$branch"  # 拉取最新的上游分支内容
            else
              git checkout -b "$branch" "upstream/$branch"  # 创建新分支并切换到该分支
            fi
            git push origin "$branch"  # 推送到你的仓库
          done

      - name: Push tags
        run: |
          git fetch --tags
          git push --tags

      - name: Cleanup
        run: |
          git gc --prune=now
